export const SET_SELF_CHECK_PERC = 'SET_SELF_CHECK_PERC';
export const RESET_SELF_CHECK_PERC = 'RESET_SELF_CHECK_PERC';
export const SET_DANGER_PERC = 'SET_DANGER_PERC';
export const RESET_DANGER_PERC = 'RESET_DANGER_PERC';
export const SET_FORM_DATA = 'SET_FORM_DATA';
export const RESET_SET_FORM_DATA = 'RESET_SET_FORM_DATA';